### ISSUE TITLE
FileNotFoundException stacktrace at startup

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#139]
**ItemPhysic version:** [v1.4.14_mc1.16.4](https://www.curseforge.com/minecraft/mc-mods/itemphysic/files/3144607)
**CreativeCore version:** [v2.0.10_mc1.16.4](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3128357)
**Forge version:** 1.16.5-36.0.0

```
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: java.io.FileNotFoundException: creativecore:gui/default_style.json
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:63)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:61)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at team.creative.creativecore.common.gui.style.GuiStyle.reload(GuiStyle.java:33)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at team.creative.creativecore.client.CreativeCoreClient.init(CreativeCoreClient.java:31)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at team.creative.creativecore.CreativeCore.client(CreativeCore.java:44)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[Worker-Main-14/INFO]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[Worker-Main-14/ERROR]: Could not load default style
```
*This was reproduced with only ItemPhysic and CreativeCore present*

**Comment by ChloeDawn** [comment]
https://github.com/CreativeMD/CreativeCore/issues/102
