### ISSUE TITLE
Help 1.18.2 ver isn't working when i load into a world

### ISSUE THREAD

**Issue by mixiymixinout** [CreativeMD/ItemPhysic#169]
Minecraft keeps freezing when trying to create/load into a world

there is no crash log ;-;

**Comment by CreativeMD** [comment]
Are you using Forge or Fabric and which version? What mods are installed? I need more information to help out. You can send the latest.log (but this only works if the last time you launched the game was the freeze).

**Comment by mixiymixinout** [comment]
I'm using forge, 

and this is the last crash report I for yesterday 
---- Minecraft Crash Report ----
// Don't do that.

Time: 7/6/22, 11:17 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: 'name' is an invalid type
	at team.creative.creativecore.common.util.ingredient.CreativeIngredient.load(CreativeIngredient.java:62) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.util.ingredient.CreativeIngredient$1.readElement(CreativeIngredient.java:116) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.util.ingredient.CreativeIngredient$1.readElement(CreativeIngredient.java:110) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$SimpleConfigTypeConveration.readElement(ConfigTypeConveration.java:799) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeList.readElement(ConfigTypeList.java:41) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeList.readElement(ConfigTypeList.java:26) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:180) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:66) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$8.readElement(ConfigTypeConveration.java:642) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$8.readElement(ConfigTypeConveration.java:637) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:180) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:66) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$8.readElement(ConfigTypeConveration.java:642) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$8.readElement(ConfigTypeConveration.java:637) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:180) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:66) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.event.ConfigEventHandler.load(ConfigEventHandler.java:225) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.event.ConfigEventHandler.load(ConfigEventHandler.java:238) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at team.creative.creativecore.common.config.event.ConfigEventHandler.startServer(ConfigEventHandler.java:87) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_21_ConfigEventHandler_startServer_ServerAboutToStartEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:86) ~[forge-1.18.2-40.1.54-universal.jar%2359!/:?] {re:classloading}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 548883576 bytes (523 MiB) / 1476395008 bytes (1408 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2187
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1123
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 16827.45
	Virtual memory used (MB): 10556.94
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 446.17
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:creativecore (incompatible), mod:itemphysic (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.1.54-universal.jar                |Forge                         |forge                         |40.1.54             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		CreativeCore_FORGE_v2.6.12_mc1.18.2.jar           |CreativeCore                  |creativecore                  |2.6.12              |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_v1.4.23_mc1.18.2.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |Manifest: NOSIGNATURE

**Comment by mixiymixinout** [comment]
> I'm using forge,
> 
> and this is the last crash report I for yesterday 

---- Minecraft Crash Report ---- // Don't do that.
> 
> Time: 7/6/22, 11:17 PM Description: Exception in server tick loop
> 
> java.lang.IllegalArgumentException: 'name' is an invalid type at team.creative.creativecore.common.util.ingredient.CreativeIngredient.load(CreativeIngredient.java:62) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.util.ingredient.CreativeIngredient$1.readElement(CreativeIngredient.java:116) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.util.ingredient.CreativeIngredient$1.readElement(CreativeIngredient.java:110) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeConveration$SimpleConfigTypeConveration.readElement(ConfigTypeConveration.java:799) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeList.readElement(ConfigTypeList.java:41) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeList.readElement(ConfigTypeList.java:26) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:180) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:66) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeConveration$8.readElement(ConfigTypeConveration.java:642) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeConveration$8.readElement(ConfigTypeConveration.java:637) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:180) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:66) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeConveration$8.readElement(ConfigTypeConveration.java:642) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeConveration$8.readElement(ConfigTypeConveration.java:637) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:180) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:66) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.event.ConfigEventHandler.load(ConfigEventHandler.java:225) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.event.ConfigEventHandler.load(ConfigEventHandler.java:238) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at team.creative.creativecore.common.config.event.ConfigEventHandler.startServer(ConfigEventHandler.java:87) ~[CreativeCore_FORGE_v2.6.12_mc1.18.2.jar%2352!/:2.6.12] {re:classloading} at net.minecraftforge.eventbus.ASMEventHandler_21_ConfigEventHandler_startServer_ServerAboutToStartEvent.invoke(.dynamic) ~[?:?] {} at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {} at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:86) ~[forge-1.18.2-40.1.54-universal.jar%2359!/:?] {re:classloading} at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B} at java.lang.Thread.run(Thread.java:833) [?:?] {}
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- System Details -- Details: Minecraft Version: 1.18.2 Minecraft Version ID: 1.18.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 17.0.1, Microsoft Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft Memory: 548883576 bytes (523 MiB) / 1476395008 bytes (1408 MiB) up to 2147483648 bytes (2048 MiB) CPUs: 12 Processor Vendor: GenuineIntel Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz Identifier: Intel64 Family 6 Model 165 Stepping 3 Microarchitecture: unknown Frequency (GHz): 2.90 Number of physical packages: 1 Number of physical CPUs: 6 Number of logical CPUs: 12 Graphics card #0 name: NVIDIA GeForce GTX 1650 SUPER Graphics card #0 vendor: NVIDIA (0x10de) Graphics card #0 VRAM (MB): 4095.00 Graphics card #0 deviceId: 0x2187 Graphics card #0 versionInfo: DriverVersion=30.0.15.1123 Memory slot #0 capacity (MB): 8192.00 Memory slot #0 clockSpeed (GHz): 2.67 Memory slot #0 type: DDR4 Virtual memory max (MB): 16827.45 Virtual memory used (MB): 10556.94 Swap memory total (MB): 8704.00 Swap memory used (MB): 446.17 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Server Running: true Player Count: 0 / 8; [] Data Packs: vanilla, mod:forge, mod:creativecore (incompatible), mod:itemphysic (incompatible) World Generation: Stable Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge' ModLauncher: 9.1.3+9.1.3+main.9b69c82a ModLauncher launch target: forgeclient ModLauncher naming: srg ModLauncher services: mixin PLUGINSERVICE eventbus PLUGINSERVICE slf4jfixer PLUGINSERVICE object_holder_definalize PLUGINSERVICE runtime_enum_extender PLUGINSERVICE capability_token_subclass PLUGINSERVICE accesstransformer PLUGINSERVICE runtimedistcleaner PLUGINSERVICE mixin TRANSFORMATIONSERVICE fml TRANSFORMATIONSERVICE FML Language Providers: minecraft@1.0 lowcodefml@null javafml@null Mod List: client-1.18.2-20220404.173914-srg.jar |Minecraft |minecraft |1.18.2 |DONE |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0🇩🇪ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f forge-1.18.2-40.1.54-universal.jar |Forge |forge |40.1.54 |DONE |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 CreativeCore_FORGE_v2.6.12_mc1.18.2.jar |CreativeCore |creativecore |2.6.12 |DONE |Manifest: NOSIGNATURE ItemPhysic_v1.4.23_mc1.18.2.jar |ItemPhysic |itemphysic |1.6.0 |DONE |Manifest: NOSIGNATURE

**Comment by CreativeMD** [comment]
Delete the config file `itemphysic.json`.
