### ISSUE TITLE
1.19.2 Game Crash when trying to change burningItems etc. in /cmdconfig

### ISSUE THREAD

**Issue by Hiconel** [CreativeMD/ItemPhysic#173]
When I try to click on either swimmingItems, burningItems or undestroyableItems in /cmdconfig the game crashes
Tested with just ItemPhysic Full and CreativeCore installed and Forge 43.1.34

Here is the crash report:

---- Minecraft Crash Report ----
// Don't do that.

Time: 2022-10-08 14:19:40
Description: mouseClicked event handler

java.lang.ClassCastException: class team.creative.creativecore.common.util.text.content.ContentItemStack cannot be cast to class net.minecraft.network.chat.FormattedText (team.creative.creativecore.common.util.text.content.ContentItemStack is in module creativecore@2.8.6 of loader 'TRANSFORMER' @1921994e; net.minecraft.network.chat.FormattedText is in module minecraft@1.19.2 of loader 'TRANSFORMER' @1921994e)
	at team.creative.creativecore.client.render.text.CompiledText$CompiledLine.add(CompiledText.java:243) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.client.render.text.CompiledText.compileNext(CompiledText.java:130) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.client.render.text.CompiledText.compileNext(CompiledText.java:111) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.client.render.text.CompiledText.compile(CompiledText.java:102) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.client.render.text.CompiledText.setText(CompiledText.java:91) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.controls.simple.GuiLabel.setTitle(GuiLabel.java:54) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.gui.GuiInfoStackButton.<init>(GuiInfoStackButton.java:28) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.util.ingredient.CreativeIngredient$1.createControls(CreativeIngredient.java:134) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$SimpleConfigTypeConveration.createControls(ConfigTypeConveration.java:927) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeList.loadValue(ConfigTypeList.java:111) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeList.loadValue(ConfigTypeList.java:29) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.gui.GuiConfigControl.init(GuiConfigControl.java:59) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.gui.ConfigGuiLayer.loadHolder(ConfigGuiLayer.java:111) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.gui.ConfigGuiLayer.lambda$loadHolder$2(ConfigGuiLayer.java:102) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.controls.simple.GuiButton.mouseClicked(GuiButton.java:27) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.GuiParent.mouseClicked(GuiParent.java:408) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.controls.parent.GuiScrollY.mouseClicked(GuiScrollY.java:90) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.GuiParent.mouseClicked(GuiParent.java:408) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.GuiLayer.mouseClicked(GuiLayer.java:199) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.integration.ScreenEventListener.m_6375_(ScreenEventListener.java:78) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:294) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.34.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at team.creative.creativecore.client.render.text.CompiledText$CompiledLine.add(CompiledText.java:243) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.client.render.text.CompiledText.compileNext(CompiledText.java:130) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.client.render.text.CompiledText.compileNext(CompiledText.java:111) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.client.render.text.CompiledText.compile(CompiledText.java:102) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.client.render.text.CompiledText.setText(CompiledText.java:91) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.controls.simple.GuiLabel.setTitle(GuiLabel.java:54) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.gui.GuiInfoStackButton.<init>(GuiInfoStackButton.java:28) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.util.ingredient.CreativeIngredient$1.createControls(CreativeIngredient.java:134) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$SimpleConfigTypeConveration.createControls(ConfigTypeConveration.java:927) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeList.loadValue(ConfigTypeList.java:111) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeList.loadValue(ConfigTypeList.java:29) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.gui.GuiConfigControl.init(GuiConfigControl.java:59) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.gui.ConfigGuiLayer.loadHolder(ConfigGuiLayer.java:111) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.config.gui.ConfigGuiLayer.lambda$loadHolder$2(ConfigGuiLayer.java:102) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.controls.simple.GuiButton.mouseClicked(GuiButton.java:27) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.GuiParent.mouseClicked(GuiParent.java:408) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.controls.parent.GuiScrollY.mouseClicked(GuiScrollY.java:90) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.GuiParent.mouseClicked(GuiParent.java:408) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.GuiLayer.mouseClicked(GuiLayer.java:199) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at team.creative.creativecore.common.gui.integration.ScreenEventListener.m_6375_(ScreenEventListener.java:78) ~[CreativeCore_FORGE_v2.8.6_mc1.19.2.jar%23145!/:2.8.6] {re:classloading}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:294) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
-- Affected screen --
Details:
	Screen name: team.creative.creativecore.common.gui.integration.ContainerScreenIntegration
Stacktrace:
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.34.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Peacegangsta'/144, l='ClientLevel', x=96.84, y=69.00, z=-119.30]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,67,-128), Section: (at 0,3,0 in 7,4,-8; chunk contains blocks 112,-64,-128 to 127,319,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 349 game time, 349 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:717) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.34.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

**Comment by CreativeMD** [comment]
Fixed this issue in the newest version of CreativeCore (should be available in a few minutes). Thank you so much for reporting this issue, quite an important one to figure out and fix.
