### ISSUE TITLE
minecraft:moss_block does not float

### ISSUE THREAD

**Issue by robotter112** [CreativeMD/ItemPhysic#192]
Minecraft: **1.20.2**
Fabric: **0.15.7**
Mod: **1.6.12**

I'm trying to set moss blocks, moss carpet and azalea to float, but no matter what I put in itemphysik.json, it won't work.

This is what I have tried to enter:
```
{
  "general": {
    "customThrow": true,
    "fallSounds": true,
    "disableCactusDamage": true,
    "swimmingItems": {
      "entries": [
        "{block:\"minecraft:moss_block\",id:\"block\"}",
        "{id:\"blocktag\",tag:\"minecraft:moss_block\"}",
        "{id:\"item\",item:\"minecraft:moss_block\"}",
        "{block:\"minecraft:moss_carpet\",id:\"block\"}",
      ],
      "isWhitelist": true
```

**Comment by CreativeMD** [comment]
Use the command /cmdconfig and configure it there. That is a lot easier and is changed immediately.

**Comment by robotter112** [comment]
When I use /cmdconfig and want to add floating items, the game crashes. Does the command only work in single player?

```
[07:46:52] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(Object)" because "this.canBeModified" is null
	at team.creative.creativecore.common.gui.controls.collection.GuiListBoxBase.createControl(GuiListBoxBase.java:47) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.gui.controls.collection.GuiListBoxBase.addAllItems(GuiListBoxBase.java:116) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.config.converation.ConfigTypeList.loadValue(ConfigTypeList.java:127) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.config.converation.ConfigTypeList.loadValue(ConfigTypeList.java:28) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.config.gui.GuiConfigControl.init(GuiConfigControl.java:75) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.config.gui.ConfigGuiLayer.loadHolder(ConfigGuiLayer.java:113) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.config.gui.ConfigGuiLayer.lambda$loadHolder$1(ConfigGuiLayer.java:104) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.gui.controls.simple.GuiButton.mouseClicked(GuiButton.java:22) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.gui.GuiParent.mouseClicked(GuiParent.java:442) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.gui.GuiParent.mouseClicked(GuiParent.java:442) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.gui.GuiParent.mouseClicked(GuiParent.java:442) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.gui.GuiParent.mouseClicked(GuiParent.java:442) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]
	at team.creative.creativecore.common.gui.controls.parent.GuiScrollY.mouseClicked(GuiScrollY.java:102) ~[CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar:?]

```

**Comment by CreativeMD** [comment]
There is an issue with CreativeCore in this version. I highly recommend to use 1.20.1 instead.
