### ISSUE TITLE
Client crash with translocators

### ISSUE THREAD

**Issue by Sir-Will** [CreativeMD/ItemPhysic#24]
Version: ItemPhysic Lite 1.3.3 mc1.10

```
java.lang.NullPointerException: Rendering Block Entity
	at com.creativemd.itemphysic.physics.ServerPhysic.getFluid(ServerPhysic.java:437)
	at com.creativemd.itemphysic.physics.ServerPhysic.getFluid(ServerPhysic.java:425)
	at com.creativemd.itemphysic.physics.ClientPhysic.doRender(ClientPhysic.java:132)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java)
	at codechicken.lib.render.RenderUtils.renderItemUniform(RenderUtils.java:401)
	at codechicken.lib.render.RenderUtils.renderItemUniform(RenderUtils.java:371)
	at codechicken.translocator.client.render.TileTranslocatorRenderer.renderTileEntityAt(TileTranslocatorRenderer.java:70)
	at codechicken.translocator.client.render.TileTranslocatorRenderer.func_180535_a(TileTranslocatorRenderer.java:26)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.itemphysic.physics.ServerPhysic.getFluid(ServerPhysic.java:437)
	at com.creativemd.itemphysic.physics.ServerPhysic.getFluid(ServerPhysic.java:425)
	at com.creativemd.itemphysic.physics.ClientPhysic.doRender(ClientPhysic.java:132)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java)
	at codechicken.lib.render.RenderUtils.renderItemUniform(RenderUtils.java:401)
	at codechicken.lib.render.RenderUtils.renderItemUniform(RenderUtils.java:371)
	at codechicken.translocator.client.render.TileTranslocatorRenderer.renderTileEntityAt(TileTranslocatorRenderer.java:70)
	at codechicken.translocator.client.render.TileTranslocatorRenderer.func_180535_a(TileTranslocatorRenderer.java:26)

-- Block Entity Details --
Details:
	Name: itemTranslocator // codechicken.translocator.tile.TileItemTranslocator
	Block type: ID #2512 (tile.translocator // codechicken.translocator.block.BlockTranslocator)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1251,57,-1297), Chunk: (at 13,3,15 in -79,-82; contains blocks -1264,0,-1312 to -1249,255,-1297), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
	Actual block type: ID #2512 (tile.translocator // codechicken.translocator.block.BlockTranslocator)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
```

**Comment by CreativeMD** [comment]
Could try out this version?
https://www.dropbox.com/s/eaagw1iy6tz8xuu/ItemPhysic%20Lite%201.3.4%20mc1.10.2.jar?dl=1

**Comment by Sir-Will** [comment]
Seems to work.

**Comment by CreativeMD** [comment]
Good to hear that, is now officially released.
