### ISSUE TITLE
java.lang.NoClassDefFoundError while loading MineCraft.

### ISSUE THREAD

**Issue by Zarepheth** [CreativeMD/ItemPhysic#26]
While attempting to load the game with this mod installed (along with a ton of other mods), the loader failed with this error:

```
[19:05:46] [main/DEBUG] [FML/]: Injecting coremod ItemPatchingLoader {com.creativemd.itemphysic.ItemPatchingLoader} class transformers
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/creativemd/itemphysic/ItemTransformer
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.creativemd.itemphysic.ItemPatchingLoader.getASMTransformerClass(ItemPatchingLoader.java:18)
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:130)
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.creativemd.itemphysic.ItemTransformer
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:05:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more

```

Full log files:
[logs.zip](https://github.com/CreativeMD/ItemPhysic/files/749347/logs.zip)

**Comment by CreativeMD** [comment]
If you are using the full version, you need to install CreativeCore as well.

**Comment by Zarepheth** [comment]
The updated versions, and that I'm using both ItemPhysics and CreativeCore, has fixed the problem. I can play the game with those mods installed. Although I've not yet seen any effect from them (spent about an hour messing with ActuallyAdditions machines, so didn't toss much around.)
