### ISSUE TITLE
Crash Report (net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock)

### ISSUE THREAD

**Issue by Lightone** [CreativeMD/ItemPhysic#34]
try pick a tree leafs the game crash X_x (B:customPickup=true)

 tested with ItemPhysic Full 1.4.2 mc1.11.2 and CreativeCore v1.7.0 mc1.11.2

[PasteBin](https://pastebin.com/VHcSYbJ4) 
<details>
  <summary>Click to expand Crash Report Log</summary>
 `---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore v1.7.0 mc1.11.2.jar)
  ItemPatchingLoader (ItemPhysic Full 1.4.2 mc1.11.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/10/17 10:31 PM
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock
	at net.minecraft.client.renderer.color.ItemColors$6.func_186726_a(ItemColors.java:115)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:315)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:165)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:140)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:203)
	at com.creativemd.itemphysic.physics.ClientPhysic.doRender(ClientPhysic.java:245)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:19)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:415)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:810)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1757)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1582)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1359)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.color.ItemColors$6.func_186726_a(ItemColors.java:115)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:315)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:165)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:140)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:203)
	at com.creativemd.itemphysic.physics.ClientPhysic.doRender(ClientPhysic.java:245)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:19)

-- Entity being rendered --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
	Entity ID: 3556
	Entity Name: item.tile.air
	Entity's Exact location: 976.47, 69.00, -507.73
	Entity's Block location: World: (976,69,-508), Chunk: (at 0,4,4 in 61,-32; contains blocks 976,0,-512 to 991,255,-497), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Entity's Momentum: -0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderEntityItem@c4aee29
	Location: -3.19,0.00,-0.19 - World: (-4,0,-1), Chunk: (at 12,0,15 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 255.9375
	Delta: 0.8537961
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:415)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:810)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1757)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1582)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Guartinajo'/827, l='MpServer', x=979.67, y=69.00, z=-507.54]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (837,64,-570), Chunk: (at 5,4,6 in 52,-36; contains blocks 832,0,-576 to 847,255,-561), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 382415 game time, 579820 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityBat['Bat'/2690, l='MpServer', x=943.50, y=47.10, z=-429.50], EntityItem['item.item.diode'/3465, l='MpServer', x=976.72, y=66.50, z=-521.84], EntityItem['item.item.comparator'/3467, l='MpServer', x=978.88, y=67.00, z=-521.39], EntityRabbit['Rabbit'/782, l='MpServer', x=1007.08, y=72.00, z=-440.25], EntityRabbit['Rabbit'/783, l='MpServer', x=1005.86, y=72.00, z=-445.51], EntityRabbit['Rabbit'/801, l='MpServer', x=1017.22, y=67.00, z=-538.12], EntityRabbit['Rabbit'/802, l='MpServer', x=1019.77, y=67.00, z=-537.04], EntityCreeper['Creeper'/946, l='MpServer', x=1056.50, y=52.00, z=-478.50], EntityRabbit['Rabbit'/820, l='MpServer', x=1030.70, y=67.00, z=-473.50], EntityRabbit['Rabbit'/821, l='MpServer', x=1024.75, y=68.00, z=-454.49], EntitySkeleton['Skeleton'/949, l='MpServer', x=1058.50, y=61.00, z=-510.50], EntityRabbit['Rabbit'/699, l='MpServer', x=903.50, y=69.00, z=-499.50], EntityRabbit['Rabbit'/700, l='MpServer', x=909.58, y=67.00, z=-488.51], EntityRabbit['Rabbit'/702, l='MpServer', x=909.53, y=65.00, z=-476.10], EntityBat['Bat'/959, l='MpServer', x=1056.35, y=52.28, z=-478.14], EntityRabbit['Rabbit'/835, l='MpServer', x=1042.78, y=68.00, z=-535.30], EntitySkeleton['Skeleton'/963, l='MpServer', x=1058.50, y=18.00, z=-458.50], EntityRabbit['Rabbit'/836, l='MpServer', x=1049.53, y=70.00, z=-471.56], EntityRabbit['Rabbit'/709, l='MpServer', x=925.89, y=70.00, z=-512.42], EntityRabbit['Rabbit'/839, l='MpServer', x=1047.57, y=66.00, z=-437.30], EntityRabbit['Rabbit'/840, l='MpServer', x=1042.00, y=65.00, z=-433.76], EntityRabbit['Rabbit'/841, l='MpServer', x=1051.77, y=67.00, z=-442.44], EntityRabbit['Rabbit'/842, l='MpServer', x=1041.38, y=67.00, z=-437.15], EntityRabbit['Rabbit'/715, l='MpServer', x=942.62, y=70.00, z=-571.48], EntityRabbit['Rabbit'/716, l='MpServer', x=929.74, y=64.00, z=-565.50], EntityPlayerSP['Guartinajo'/827, l='MpServer', x=979.67, y=69.00, z=-507.54], EntityRabbit['Rabbit'/849, l='MpServer', x=1050.52, y=72.00, z=-521.59], EntityRabbit['Rabbit'/729, l='MpServer', x=955.55, y=67.00, z=-576.40], EntityRabbit['Rabbit'/730, l='MpServer', x=953.47, y=70.00, z=-573.25], EntityItem['item.tile.air'/3556, l='MpServer', x=976.47, y=69.00, z=-507.73], EntityCow['Cow'/764, l='MpServer', x=984.59, y=70.00, z=-473.73]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 216889704 bytes (206 MB) / 690933760 bytes (658 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 Optifine OptiFine_1.11.2_HD_U_B7 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAAAAAAA	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAAAAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAAAAAAA	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAAAAAAA	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.7.0 mc1.11.2.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore v1.7.0 mc1.11.2.jar)
  
ItemPatchingLoader (ItemPhysic Full 1.4.2 mc1.11.2.jar)
  com.creativemd.itemphysic.ItemTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2228
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.11.2-rv4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.3304
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4`
</details>

**Comment by CreativeMD** [comment]
Could not reproduce this bug either, could send me a screenshot of it?

**Comment by Lightone** [comment]
only happend one time, i try again but nothing happend  xD. if not happend with other people is no a big deal.

Dont worry by happy =D.

![2017-04-13_14 00 22](https://cloud.githubusercontent.com/assets/2113099/25020226/22e92c0c-2053-11e7-974f-91ba6aa37a3a.png)

**Comment by CreativeMD** [comment]
Ok if it will happen again just reopen this issue. Thanks for reporting.
