### ISSUE TITLE
ItemPhysic and CreativeCore

### ISSUE THREAD

**Issue by Tereo725** [CreativeMD/ItemPhysic#60]
I tried to use Itemphysics and i got this error-log
We're using a minecraft 1.12.2 server with a few weeks old forge version 

```
[19:16:21] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:52]: [itemphysic] Patched net.minecraft.entity.item.EntityItem ...
[19:16:21] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge_server.jar:?]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge_server.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/item/EntityItem
at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.item.EntityItem
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
... 12 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.creativemd.itemphysic.ItemTransformer@3c3a0032 from coremod ItemPatchingLoader
at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge_server.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
... 12 more
Caused by: java.lang.NullPointerException
at com.creativemd.itemphysic.ItemTransformer$3.transform(ItemTransformer.java:162) ~[ItemTransformer$3.class:?]
at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:46) ~[CreativeTransformer.class:?]
at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:33) ~[CreativeTransformer.class:?]
at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge_server.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
... 12 more
```

Any Ideas what went wrong or how i could fix it?

**Comment by CreativeMD** [comment]
Can you send me the entire crash-report? I want to know which mods and versions you are using. Maybe you downloaded a version for 1.11.2?

**Comment by CreativeMD** [comment]
This should be fixed in the newest CreativeCore and ItemPhysic version. If not just reopen the issue.
