### ISSUE TITLE
Game crashes while starting 1.12.2; Linux Mint 19.1 Tessa

### ISSUE THREAD

**Issue by rosenclosed** [CreativeMD/ItemPhysic#84]
I have a problem, Starting this mod in 1.12.2 with forge installed correctly (all other mods work) the game crashes launcher log gives me the following infos:

```
[0425/165715:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:15] [main/INFO] [FML]: Searching /home/admin/.minecraft/mods for mods

[0425/165715:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:15] [main/WARN] [FML]: The coremod com.creativemd.itemphysic.ItemPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft

[0425/165715:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:15] [main/WARN] [FML]: The coremod ItemPatchingLoader (com.creativemd.itemphysic.ItemPatchingLoader) is not signed!

[0425/165715:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[0425/165715:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker

[0425/165715:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[0425/165715:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[0425/165715:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info Exception in thread "main" [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/creativemd/itemphysic/ItemTransformer

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.creativemd.itemphysic.ItemPatchingLoader.getASMTransformerClass(ItemPatchingLoader.java:16)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:128)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.creativemd.itemphysic.ItemTransformer

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/transformer/CreativeTransformer

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.transformer.CreativeTransformer

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[0425/165716:INFO:GameCallbacks.cpp(198)] game/game () info [16:57:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	... 10 more

[0425/165716:INFO:GameCallbacks.cpp(198)] launcher/monitor (Process Monitor) fatal Process crashed with exit code 1

[0425/165716:INFO:GameCallbacks.cpp(34)] Destroying GameCallbacks!

[0425/165716:INFO:ClientHandler.cpp(274)] Launcher is already open!

[0425/165716:INFO:ClientHandler.cpp(1049)] GameStarter: Previous instance closed
[launcher_log.txt](https://github.com/CreativeMD/ItemPhysic/files/3117541/launcher_log.txt)

``` 
@CreativeMD I would play your mod lovingly but it just didn't work please take the time and read the log and help me or fix the bugs.

**Comment by CreativeMD** [comment]
You have to install CreativeCore as well.

**Comment by rosenclosed** [comment]
Thanks, I didn't know that
