### ISSUE TITLE
Crash with temPhysic_Full_1.4.21_mc1.12.2

### ISSUE THREAD

**Issue by furtabs** [CreativeMD/ItemPhysic#91]
When launching the game it fails to open Minecraft at all. Operating System is a Linux machine based on Ubuntu 18.04

Crash below

`[16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/creativemd/itemphysic/ItemTransformer

instancesManager.js:181 [16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.creativemd.itemphysic.ItemPatchingLoader.getASMTransformerClass(ItemPatchingLoader.java:16)
[16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)

instancesManager.js:181 [16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)

instancesManager.js:181 [16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.creativemd.itemphysic.ItemTransformer
[16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:58:41] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/transformer/CreativeTransformer
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.transformer.CreativeTransformer
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:58:41] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	... 10 more`

**Comment by furtabs** [comment]
Forgot to install Creative Core
